import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Hunting Coder</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				{/* <Image src="/coder-boy.jpg" width={200} height={200} className={styles.headImg}></Image> */}
				<img src="/coder-boy.jpg" width={200} height={200} className={styles.headImg}></img>
				<h1 className={styles.title}>
					Hunting Coder
				</h1>

				<p className={styles.description}>
					A blog for hunting coder by a hunting coder
				</p>

				<h2 className={styles.blogTitle} style={{ fontSize: '2rem' }}>Latest Blogs</h2>

				<div className={styles.grid}>
					<Link href="/blogpost/test" className={styles.card}>
						<h3>Documentation</h3>
						<p>Find in-depth information about Next.js features and API.</p>
					</Link>

					<Link href="/blogpost/test" className={styles.card}>
						<h3>Learn</h3>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</Link>

					<Link
						href="/blogpost/test"
						className={styles.card}
					>
						<h3>Examples</h3>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</Link>

					<Link
						href="/blogpost/test"
						className={styles.card}
					>
						<h3>Deploy</h3>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</Link>
				</div>
			</main>
		</div>
	)
}
